# Generated by Django 4.1.7 on 2023-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('accountNo', models.BigIntegerField()),
                ('sortCode', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=20)),
                ('customerId', models.BigIntegerField()),
                ('totalBalance', models.FloatField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('mobileNo', models.CharField(max_length=20, null=True)),
                ('zipCode', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverCustomerName', models.CharField(max_length=20)),
                ('receiverAccountNo', models.BigIntegerField()),
                ('receiverSortCode', models.CharField(max_length=20)),
                ('transactionType', models.CharField(max_length=20)),
                ('customerId', models.BigIntegerField(default=None, null=True)),
                ('amount', models.FloatField(default=0)),
                ('totalBalance', models.FloatField(max_length=40)),
            ],
        ),
    ]
