# Generated by Django 4.1.7 on 2023-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('accountNo', models.BigIntegerField()),
                ('sortCode', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=20)),
                ('totalBalance', models.FloatField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverCustomerName', models.CharField(max_length=20)),
                ('receiverAccountNo', models.BigIntegerField()),
                ('receiverSortCode', models.CharField(max_length=20)),
                ('transactionType', models.CharField(max_length=20)),
                ('totalBalance', models.FloatField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
