# Generated by Django 4.1.7 on 2023-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_customerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiverSortCode',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiverAccountNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='totalBalance',
            field=models.FloatField(default=0),
        ),
    ]
