# Generated by Django 4.1.7 on 2023-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_transaction_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
    ]
