# Generated by Django 4.1.7 on 2023-03-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiverAccountNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiverCustomerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
