# Generated by Django 4.1.7 on 2023-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_receiveraccountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiverSortCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(max_length=40),
        ),
    ]
