# Generated by Django 4.1.7 on 2023-03-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
